#!/bin/bash

echo "🚀 COMANDOS RÁPIDOS - TERMUX"
echo "============================"
echo ""
echo "📦 SISTEMA:"
echo "  update          - Atualizar tudo"
echo "  install <pkg>   - Instalar pacote"
echo "  storage         - Acessar armazenamento"
echo ""
echo "🔧 GIT:"
echo "  gs              - status"
echo "  ga <file>       - add"
echo "  gc \"msg\"       - commit"
echo "  gco <branch>    - checkout"
echo "  gpush           - push automático"
echo ""
echo "🐍 PYTHON:"
echo "  py <script.py>  - executar"
echo "  pipi <pkg>      - instalar"
echo "  venv            - criar virtualenv"
echo ""
echo "📁 PROJETOS:"
echo "  mkcd <nome>     - criar e entrar"
echo "  backup          - backup rápido"
echo "  ll              - lista detalhada"
echo ""
echo "🚀 TRINITY:"
echo "  trinity         - ir para diretório"
echo "  start-trinity   - iniciar sistema"
echo ""
echo "❓ AJUDA:"
echo "  help-menu       - menu completo"
echo "  commands        - lista rápida"
echo ""
echo "🇧🇷 Digite o comando e pressione Enter!"
